// This file is auto-generated by the payload generate:importmap command
// It maps component paths used in the admin panel to their actual locations

export default {
  '@/components/StreamStatusBanner': () => import('./components/StreamStatusBanner'),
  '@/components/admin/NotificationsPanel': () => import('./components/admin/NotificationsPanel'),
}
