// This file is auto-generated by the payload generate:importmap command
// Manual additions for custom components
import DRMBadgeCell from './collections/VideoAssets/components/DRMBadgeCell'

export default {
  // Add custom components here if needed
  '@/collections/VideoAssets/components/DRMBadgeCell': DRMBadgeCell,
}
